spring:
  application:
    name: shopping-cart
  config:
    import: "configserver:"

  cloud:
    config:
      discovery:
        enabled: true           # клиент должен использовать службу обнаружения (Eureka) для поиска сервера конфигураци
        serviceId: config-server
      fail-fast: true           # если сервер конфигурации недоступен, сразу "падать"
      retry:
        useRandomPolicy: true   # для повторных попыток использовать стратегию random exponential backoff. Каждая последующая попытка переподключения совершается через всё больший случайный интервал времени
        max-interval: 6000      # максимально возможный интервал между попытками подключения

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/